import { Product } from "./types/Product";

export const productsSample: Product[] = [
  {
    name: "Nikle slim short",
    slug: "nike-slim-short",
    category: "shirts",
    image: "../images/p1.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "High quality shirts",
  },
  {
    name: "Nikle Pant",
    slug: "nike-pant",
    category: "pants",
    image: "../images/p2.jpg",
    price: 100,
    countInStock: 8,
    brand: "Nike",
    rating: 4.4,
    numReviews: 20,
    description: "High quality Pants",
  },
  {
    name: "Shoes",
    slug: "black-shoes",
    category: "shoes",
    image: "../images/p3.jpg",
    price: 80,
    countInStock: 0,
    brand: "Bata",
    rating: 5,
    numReviews: 30,
    description: "High quality shoes",
  },
  {
    name: "Glass",
    slug: "smart-glasses",
    category: "Glasses",
    image: "../images/p4.jpg",
    price: 50,
    countInStock: 100,
    brand: "Robin",
    rating: 4.8,
    numReviews: 33,
    description: "High quality glasses",
  },
];
